name: Deploy to Docker Hub
on:
  workflow_dispatch:
    inputs:
      duckdb_version:
        description: DuckDB version to deploy. Without leading 'v'!
        type: string
        required: true
      set_as_latest:
        description: Set this version as the 'latest' on Docker?
        type: boolean
        default: false
      build_distroless:
        description: Build distroless image (duckdb/duckdb)
        type: boolean
        default: true
      build_shell:
        description: Build shell image (duckdb/duckdb-shell)
        type: boolean
        default: true

jobs:
  distroless:
    if: ${{ inputs.build_distroless }}
    uses: ./.github/workflows/build-distroless.yml
    with:
      image_name: duckdb/duckdb
      duckdb_version: ${{ inputs.duckdb_version }}
      set_as_latest: ${{ inputs.set_as_latest }}
    secrets: inherit

  shell:
    if: ${{ inputs.build_shell }}
    uses: ./.github/workflows/build-shell.yml
    with:
      image_name: duckdb/duckdb-shell
      duckdb_version: ${{ inputs.duckdb_version }}
      set_as_latest: ${{ inputs.set_as_latest }}
    secrets: inherit
