name: Deploy
on:
  workflow_call:
    inputs:
      duckdb_version:
        description: The DuckDB version to deploy. Without leading 'v'!
        type: string
        required: true
      set_as_latest:
        description: Whether to set this version as the latest on Docker
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      duckdb_version:
        type: string
        required: true
      set_as_latest:
        type: boolean   
        default: false

jobs:
 docker-upload:
   runs-on: ubuntu-latest
   if: ${{ inputs.duckdb_version != '' }}
   env:
     VER: ${{ inputs.duckdb_version }}
     PKG: hfmuehleisen/duckdb-testing
   steps:
     - name: Setup Builder
       shell: bash
       run: |
        docker buildx create --name duckdb_builder
        docker buildx use duckdb_builder

     - name: Create and test Image
       shell: bash
       run: |
        curl -s -L -o duckdb_cli-linux-amd64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-amd64.zip"
        curl -s -L -o duckdb_cli-linux-arm64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-arm64.zip"
        unzip -p duckdb_cli-linux-amd64.zip duckdb > duckdb_amd64
        unzip -p duckdb_cli-linux-arm64.zip duckdb > duckdb_arm64
        chmod +x duckdb_*

        cat > Dockerfile <<- EOM
        FROM gcr.io/distroless/cc-debian12
        ARG TARGETPLATFORM
        ARG TARGETARCH
        COPY duckdb_\$TARGETARCH /duckdb
        CMD ["/duckdb"]
        ENV PATH="\$PATH:/"
        EOM

        docker buildx build --platform linux/amd64,linux/arm64 -t $PKG:$VER .
        docker buildx build --load -t $PKG:$VER .

        REPORTED_VER=`docker run --rm $PKG:$VER duckdb -csv -noheader -c "SELECT version()"`

        if [ $REPORTED_VER != "v$VER" ]
        then
          echo "Failed version check for $VER, got $REPORTED_VER"
          exit 1
        fi

     - name: Upload to hub.docker.com
       shell: bash
       env:
        DOCKER_USERNAME: hfmuehleisen
        DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
       run: |
        if [ ${{ inputs.set_as_latest }} == 1 ]
        then
          docker tag $PKG:$VER $PKG:latest
        fi
        docker login
        docker buildx build --platform linux/amd64,linux/arm64 -t $PKG:$VER --push .
