# TODO should we use releases for this instead? move to duckdb main?

name: Deploy
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: Docker image name, e.g. 'duckdb/duckdb'
        type: string
        required: true
        default:  'hfmuehleisen/duckdb-testing'
      duckdb_version:
        description: DuckDB version to deploy. Without leading 'v'!
        type: string
        required: true
      set_as_latest:
        description: Set this version as the 'latest' on Docker?
        type: boolean
        default: false

env:
  IMAGE_NAME: ${{ inputs.image_name }}
  TEST_TAG: ${{ inputs.image_name }}:test
  LATEST_TAG: ${{ inputs.image_name }}:latest
  VER: ${{ inputs.duckdb_version }}
  VER_TAG: ${{ inputs.image_name }}:${{ inputs.duckdb_version }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Download DuckDB binaries
        shell: bash
        run: |
         curl -s -L -o duckdb_cli-linux-amd64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-amd64.zip"
         curl -s -L -o duckdb_cli-linux-arm64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-arm64.zip"
         unzip -p duckdb_cli-linux-amd64.zip duckdb > duckdb_amd64
         unzip -p duckdb_cli-linux-arm64.zip duckdb > duckdb_arm64
         chmod +x duckdb_*
         ls

      - name: Create Dockerfile
        shell: bash
        run: |
         cat > Dockerfile <<- EOM
         FROM gcr.io/distroless/cc-debian12
         ARG TARGETPLATFORM
         ARG TARGETARCH
         COPY duckdb_\$TARGETARCH /duckdb
         CMD ["/duckdb"]
         ENV PATH="\$PATH:/"
         EOM

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          REPORTED_VER=`docker run --rm ${{ env.TEST_TAG }} duckdb -csv -noheader -c "SELECT version()"`

          if [ $REPORTED_VER != "v$VER" ]
          then
            echo "Failed version check for $VER, got $REPORTED_VER"
            exit 1
          fi

      - name: Build and push ${{ inputs.duckdb_version }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ env.VER_TAG }}

# jobs:
#  docker-upload:
#    runs-on: ubuntu-latest
#    if: ${{ inputs.duckdb_version != '' }}
#    env:
#      VER: ${{ inputs.duckdb_version }}
#      PKG: hfmuehleisen/duckdb-testing
#    steps:
#      - name: Setup Builder
#        shell: bash
#        run: |
#         docker buildx create --name duckdb_builder
#         docker buildx use duckdb_builder

#      - name: Create and test Image
#        shell: bash
#        run: |
#         curl -s -L -o duckdb_cli-linux-amd64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-amd64.zip"
#         curl -s -L -o duckdb_cli-linux-arm64.zip "https://install.duckdb.org/v$VER/duckdb_cli-linux-arm64.zip"
#         unzip -p duckdb_cli-linux-amd64.zip duckdb > duckdb_amd64
#         unzip -p duckdb_cli-linux-arm64.zip duckdb > duckdb_arm64
#         chmod +x duckdb_*

#         cat > Dockerfile <<- EOM
#         FROM gcr.io/distroless/cc-debian12
#         ARG TARGETPLATFORM
#         ARG TARGETARCH
#         COPY duckdb_\$TARGETARCH /duckdb
#         CMD ["/duckdb"]
#         ENV PATH="\$PATH:/"
#         EOM

#         docker buildx build --platform linux/amd64,linux/arm64 -t $PKG:$VER .
#         docker buildx build --load -t $PKG:$VER .

#         REPORTED_VER=`docker run --rm $PKG:$VER duckdb -csv -noheader -c "SELECT version()"`

#         if [ $REPORTED_VER != "v$VER" ]
#         then
#           echo "Failed version check for $VER, got $REPORTED_VER"
#           exit 1
#         fi

#      - name: Upload to hub.docker.com
#        shell: bash
#        env:
#         DOCKER_USERNAME: hfmuehleisen
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#        run: |
#         if [ ${{ inputs.set_as_latest }} == 1 ]
#         then
#           docker tag $PKG:$VER $PKG:latest
#         fi
#         docker buildx build --platform linux/amd64,linux/arm64 -t $PKG:$VER --push .
